pipeline {
    agent any

    stages {
        stage('Deploy - Docker Image') {
            steps {
                sh "docker run --name python_service trilhajt/pythonserver"              
            }
        }

        post {
            always {
                archiveArtifacts artifacts: 'artefatosDeploy.txt'
            }
        }
    }
}
