pipeline {
    agent any

    stages {
        stage('Packer - Bake Docker Image') {
            steps {
                sh "packer build bake-docker.pkr.hcl"              
            }
        }
    }
}